import {
  webDarkTheme,
  webLightTheme,
  type Theme,
} from '@fluentui/react-components'

const overrides = {
  fontFamilyBase:
    '"Segoe UI", Aptos, Calibri, -apple-system, BlinkMacSystemFont, sans-serif',
  fontFamilyMonospace: 'Consolas, "Courier New", Courier, monospace',
  borderRadiusMedium: '0.625rem',
  borderRadiusNone: '0px',
  borderRadiusLarge: '1rem',
  shadow4: 'var(--cp-shadow-card)',
  colorNeutralBackground1: 'var(--cp-surface)',
  colorNeutralBackground1Hover: 'var(--cp-surface-soft)',
  colorNeutralBackground1Pressed: 'var(--cp-border)',
  colorNeutralBackground1Selected: 'var(--cp-surface-soft)',
  colorNeutralBackground2: 'var(--cp-bg-elevated)',
  colorNeutralBackground2Hover: 'var(--cp-surface-soft)',
  colorNeutralBackground2Pressed: 'var(--cp-border)',
  colorNeutralBackground2Selected: 'var(--cp-surface-soft)',
  colorNeutralBackground3: 'var(--cp-surface-soft)',
  colorNeutralBackground4: 'var(--cp-bg)',
  colorNeutralBackgroundDisabled: 'var(--cp-surface-soft)',
  colorNeutralForeground1: 'var(--cp-text)',
  colorNeutralForeground1Hover: 'var(--cp-text)',
  colorNeutralForeground1Pressed: 'var(--cp-text)',
  colorNeutralForeground1Selected: 'var(--cp-text)',
  colorNeutralForeground2: 'var(--cp-text-muted)',
  colorNeutralForeground2Hover: 'var(--cp-text)',
  colorNeutralForeground2Pressed: 'var(--cp-text)',
  colorNeutralForeground2Selected: 'var(--cp-text)',
  colorNeutralForeground2BrandHover: 'var(--cp-accent)',
  colorNeutralForeground2BrandPressed: 'var(--cp-accent-hover)',
  colorNeutralForeground2BrandSelected: 'var(--cp-accent)',
  colorNeutralForeground3: 'var(--cp-text-soft)',
  colorNeutralForegroundDisabled: 'var(--cp-text-soft)',
  colorNeutralForegroundOnBrand: 'var(--cp-accent-fg)',
  colorNeutralStroke1: 'var(--cp-border-strong)',
  colorNeutralStroke1Hover: 'var(--cp-text-muted)',
  colorNeutralStroke1Pressed: 'var(--cp-text)',
  colorNeutralStroke1Selected: 'var(--cp-accent)',
  colorNeutralStroke2: 'var(--cp-border)',
  colorNeutralStrokeDisabled: 'var(--cp-border)',
  colorNeutralStrokeAccessible: 'var(--cp-text-muted)',
  colorCompoundBrandStroke: 'var(--cp-accent)',
  colorCompoundBrandStrokeHover: 'var(--cp-accent-hover)',
  colorCompoundBrandStrokePressed: 'var(--cp-accent-hover)',
  colorCompoundBrandBackground: 'var(--cp-accent)',
  colorCompoundBrandBackgroundHover: 'var(--cp-accent-hover)',
  colorCompoundBrandBackgroundPressed: 'var(--cp-accent-hover)',
  colorCompoundBrandForeground1: 'var(--cp-accent)',
  colorCompoundBrandForeground1Hover: 'var(--cp-accent-hover)',
  colorCompoundBrandForeground1Pressed: 'var(--cp-accent-hover)',
  colorPaletteRedBorder2: 'var(--cp-danger)',
  colorPaletteRedForeground1: 'var(--cp-danger)',
  colorStrokeFocus1: 'var(--cp-surface)',
  colorStrokeFocus2: 'var(--cp-text)',
  colorBrandBackground: 'var(--cp-accent)',
  colorBrandBackgroundHover: 'var(--cp-accent-hover)',
  colorBrandBackgroundPressed: 'var(--cp-accent-hover)',
  colorBrandBackgroundSelected: 'var(--cp-accent-hover)',
  colorBrandBackground2: 'var(--cp-accent-soft)',
  colorBrandBackground2Hover: 'var(--cp-highlight)',
  colorBrandBackground2Pressed: 'var(--cp-highlight)',
  colorBrandForeground1: 'var(--cp-accent)',
  colorBrandForeground2: 'var(--cp-accent)',
  colorBrandForeground2Hover: 'var(--cp-accent-hover)',
  colorBrandForeground2Pressed: 'var(--cp-accent-hover)',
  colorBrandForegroundLink: 'var(--cp-link)',
  colorBrandForegroundLinkHover: 'var(--cp-link)',
  colorBrandForegroundLinkPressed: 'var(--cp-link)',
  colorBrandForegroundLinkSelected: 'var(--cp-link)',
  colorBrandStroke1: 'var(--cp-accent)',
  colorBrandStroke2: 'var(--cp-accent)',
  colorBrandStroke2Hover: 'var(--cp-accent-hover)',
  colorBrandStroke2Pressed: 'var(--cp-accent-hover)',
} satisfies Partial<Theme>

export const themes: Record<'light' | 'dark', Theme> = {
  light: { ...webLightTheme, ...overrides },
  dark: {
    ...webDarkTheme,
    ...overrides,
    colorNeutralForeground2: 'var(--cp-text-soft)',
  },
}
